global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pesaguard-webhook-receiver'
    metrics_path: /metrics
    static_configs:
      - targets: ['webhook_receiver:5000']

  - job_name: 'pesaguard-dashboard-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['dashboard_api:5001']

  - job_name: 'pesaguard-rq-worker'
    metrics_path: /metrics
    static_configs:
      - targets: ['rq_worker:5000']

  - job_name: 'pesaguard-otel-collector'
    metrics_path: /metrics
    static_configs:
      - targets: ['otel_collector:8888']
