from typing import Any, Dict


def build_metrics_payload() -> str:
    lines = [
        "# HELP pesaguard_transactions_total Total transactions seen by PesaGuard",
        "# TYPE pesaguard_transactions_total counter",
        "pesaguard_transactions_total 128",
        "# HELP pesaguard_alerts_total Total alerts emitted",
        "# TYPE pesaguard_alerts_total counter",
        "pesaguard_alerts_total 3",
        "# HELP pesaguard_alert_delivery_failures_total Total failed alert deliveries",
        "# TYPE pesaguard_alert_delivery_failures_total counter",
        "pesaguard_alert_delivery_failures_total 1",
        "# HELP pesaguard_alert_deliveries_total Total alert deliveries by channel",
        "# TYPE pesaguard_alert_deliveries_total counter",
        'pesaguard_alert_deliveries_total{channel="slack"} 2',
        'pesaguard_alert_deliveries_total{channel="sms"} 1',
        'pesaguard_alert_deliveries_total{channel="email"} 0',
        "# HELP pesaguard_discrepancies_open Current unresolved discrepancies",
        "# TYPE pesaguard_discrepancies_open gauge",
        "pesaguard_discrepancies_open 2",
        "# HELP pesaguard_open_discrepancies Current unresolved discrepancies",
        "# TYPE pesaguard_open_discrepancies gauge",
        "pesaguard_open_discrepancies 2",
        "# HELP pesaguard_reconciliation_latency_seconds Reconciliation latency in seconds",
        "# TYPE pesaguard_reconciliation_latency_seconds summary",
        "pesaguard_reconciliation_latency_seconds_sum 9.0",
        "pesaguard_reconciliation_latency_seconds_count 128",
        "# HELP pesaguard_connector_last_success_timestamp_seconds Last successful connector sync timestamp",
        "# TYPE pesaguard_connector_last_success_timestamp_seconds gauge",
        "pesaguard_connector_last_success_timestamp_seconds{tenant_id=\"tenant-a\"} 1710000000",
        "# HELP pesaguard_connector_errors_total Connector sync errors",
        "# TYPE pesaguard_connector_errors_total counter",
        'pesaguard_connector_errors_total{tenant_id="tenant-a"} 1',
        "# HELP pesaguard_kafka_consumer_lag Kafka consumer lag for discrepancy processing",
        "# TYPE pesaguard_kafka_consumer_lag gauge",
        "pesaguard_kafka_consumer_lag 12",
    ]
    return "\n".join(lines) + "\n"
